name: Set up environment
description: Set up a conda-recipe-manager environment

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Create Environment
      shell: bash
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      # NOTE: We use `sed` to force a Python version in the `environment.yaml` file
      run: |
        conda update -n base -c defaults conda
        source $CONDA/etc/profile.d/conda.sh
        conda init bash
        sed -i 's/- python >=3.*$/- python ${{ inputs.python-version }}.*/' environment.yaml
        conda env create -f environment.yaml --name conda-recipe-manager --yes
        conda run --name conda-recipe-manager pip install .
